includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - backbones/resnet12.yaml

data_root: /data/bzx_yjy/cifar100
image_size: 32
  
save_path: ./

# data
init_cls_num: 20
inc_cls_num: 20
task_num: 5


epoch: 170
device_ids: 0
n_gpu: 1
val_per_epoch: 5


batch_size: 128


optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 2e-4



lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [80, 120]

backbone:
  name: resnet32
  kwargs:

buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 0
    batch_size: 32
    strategy: random     # random, equal_random, reservoir, herding

classifier:
  name: GEM
  kwargs:
    num_class: 100
    feat_dim: 64
    #feat_dim: 512
    #n_hiddens: 100
    #n_layers: 2
    n_memories: 2000
    #n_outputs: 100
    n_task: 5
    memory_strength: 0